// Create user
POST http://localhost:12000/users
Content-Type: application/json

{
    "id": "60953a28-df70-4ec8-9f6d-8effd8c50cca",

    "firstName" : "Jonathon",

    "surname" : "John",

    "position" : "Software Engineer",

    "gitHubProfileUrl" : "maruf571"
}

###

// find list
GET http://localhost:12000/users
Content-Type: application/json

###

// find by id
GET http://localhost:12000/users/60953a28-df70-4ec8-9f6d-8effd8c50cca

###

// delete by id
DELETE http://localhost:12000/users/60953a28-df70-4ec8-9f6d-8effd8c50cca

###
GET http://localhost:12000/users/60953a28-df70-4ec8-9f6d-8effd8c50cca/repositories

###

